{{- if and .Values.postgresql.enabled .Values.postgresql.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "atuin.postgresql.fullname" . }}
  labels:
    {{- include "atuin.postgresql.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.postgresql.persistence.accessModes | nindent 4 }}
  {{- if .Values.postgresql.persistence.storageClass }}
  storageClassName: {{ .Values.postgresql.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size | quote }}
{{- end }}
