apiVersion: v2
name: atuin
description: A Helm chart for Atuin - magical shell history sync
type: application
version: 0.1.2
appVersion: "18.0.0"
keywords:
  - atuin
  - shell
  - history
  - sync
home: https://blog.kuepper.nrw
sources:
  - https://github.com/9it-full-service/atuin
maintainers:
  - name: Rüdiger Küpper
    url: https://github.com/ruedigerp
